### ISSUE TITLE
Asking effective questions 

### ISSUE THREAD

**Issue by mksm1228** [STAT545-UBC-hw-2019-20/Announcements#1]
URL: https://stackoverflow.com/questions/38987/how-to-merge-two-dictionaries-in-a-single-expression

From my understanding, the author wants to combine two dictionaries with different expressions into one merged dictionary with a new expression. The question is worded somewhat effectively. However, I feel the sentence about the update () method could be phrased better. For example, maybe they could have said "I tried using the update () method but instead of returning the result I want, it modified the dictionary."

**Comment by vincenzocoia** [comment]
Nice! Thanks for opening this @mksm1228 , we didn't end up getting around to this exercise. But great that you did it -- nice insight.
