### ISSUE TITLE
Rubric for peer review 1

### ISSUE THREAD

**Issue by hanrach** [STAT545-UBC-hw-2019-20/Announcements#12]
Where can I find the rubric for peer review? I'm wondering if this [rubric](https://raw.githubusercontent.com/STAT545-UBC/STAT545-home/master/content/evaluation/peer-review-template.md) is the right one, because it has graphing component which we didn't have for Assignment 1.

**Comment by yuliaUU** [comment]
Yes, the link you added is correct, this is for mat you will use to give peer review. More info can be found on [STAT454](https://stat545.stat.ubc.ca) home page under Evaluations, click on Peer Reviews and you will find detailed instructions and rubric there

**Comment by hanrach** [comment]
But did we have to produce graphs for A1?

**Comment by yuliaUU** [comment]
What does A1 mean?

**Comment by dy-lin** [comment]
I believe A1 means assignment 1 (hw01)

**Comment by yuliaUU** [comment]
thank you @dy-lin ! 
For assignment 1 you just need to demonstrate 3 functions, it is up to you which ones you want to pick. you can even try to pick functions that have not been covered in class. But make sure you meet an objective of the exercise with your data exploration.

**Comment by vincenzocoia** [comment]
Ah, I see the confusion -- the table that you link to @hanrach for the rubric just contains some components that you can look for in a submission. If there are no plots (as is the case for Assignment 1), please feel free to remove that row.
