### ISSUE TITLE
Can't access one of my peer reviewees' work

### ISSUE THREAD

**Issue by t-wang-ecohydro** [STAT545-UBC-hw-2019-20/Announcements#13]
Hello,

On the [peer review page](https://stat545.stat.ubc.ca/evaluation/hw01/pr01/), one of the links for my reviewees either isn't working, or this person's work doesn't exist. I can't seem to find them by searching the STAT545-UBC-hw-2019-20 organization repos either. Can I be reassigned another student's repo?

Thanks,
Tracy

**Comment by yuliaUU** [comment]
You can review [forouh](https://github.com/STAT545-UBC-hw-2019-20/stat545-hw-forouh)

**Comment by vittorioromaniello** [comment]
@yuliaUU  can you also see this similar issue please? https://github.com/STAT545-UBC/Discussion/issues/551
