### ISSUE TITLE
Assignment 2 Q 1.3

### ISSUE THREAD

**Issue by almas2019** [STAT545-UBC-hw-2019-20/Announcements#14]
I am a bit confused regarding the instructions for this question: 
Filter gapminder to all entries that have experienced a **drop** in life expectancy. Be sure to include a new variable that’s the **increase**  in life expectancy in your tibble. Hint: you might find the lag() or diff() functions useful.
This seems a bit contradictory.

Does this mean filter out countries that have a drop in life expectancies over all the years or only keep those have experienced a drop? 
Is it the whole gapminder dataset and not the filtered one from 1.1? Also are we looking at the general trend over all the years , or just the 1970s? 
Thank you in advance.

**Comment by armetcal** [comment]
Did you mean to close the question? I was wondering something similar. I know we're supposed to use the gapminder dataset, but I'm specifically wondering whether we're supposed to analyze:
- Any lines in the data that have a reduced life expectancy from the previous line
- Any countries that have experienced a drop in life expectancy overall
- Any rows where the country has experienced a drop in life expectancy from year to year (AKA doesn't count lines where we're changing countries)

**Comment by almas2019** [comment]
Oh I posted it here : https://github.com/STAT545-UBC/Discussion/issues/553, I'd appreciate it if you add your comment there as well

**Comment by armetcal** [comment]
Ah okay, sure!
