### ISSUE TITLE
Can't find my name in the homework repo

### ISSUE THREAD

**Issue by belalanik** [STAT545-UBC-hw-2019-20/Announcements#15]
I can't find my name in the homework repo [STAT545-UBC-hw-2019-20](https://github.com/STAT545-UBC-hw-2019-20/). I sought help from TA, still can't find my name. However, I have submitted my 1st assignment on September 15th (just copied my [repo](https://github.com/belalanik/stat545-hw-belalanik) and pasted the URL on Canvas). 

Now I seek help from instructors. 

Thanks.

**Comment by vincenzocoia** [comment]
Hi @belalanik, it's up to you to make the repo. You can find instructions on how to do so on the [assignment home page](https://stat545.stat.ubc.ca/evaluation/assignments/).

**Comment by belalanik** [comment]
Thank you very much for the instruction. I have now created a homework repo. Thanks again.
