### ISSUE TITLE
Can't access my peer reviewee's assignment 1

### ISSUE THREAD

**Issue by sean-la** [STAT545-UBC-hw-2019-20/Announcements#16]
@545a-2019-20-TA 

On the [peer review page](https://stat545.stat.ubc.ca/evaluation/hw01/pr01/), it says I need to review assignment 1 of @sallyinnis, but I'm getting a 404 error when I click their link. What should I do?

Thank you!

**Comment by yuliaUU** [comment]
Hi, she probably has not put her HW into the [STAT545-UBC-hw-2019-20](https://github.com/STAT545-UBC-hw-2019-20?utf8=%E2%9C%93&q=&type=&language=) repo, choose a random person and let us know who you chose so we keep track of it:)
