### ISSUE TITLE
output format for hw02

### ISSUE THREAD

**Issue by trevor-baker** [STAT545-UBC-hw-2019-20/Announcements#17]
I'm trying to figure out which format to knit my hw02 Rmd to. The hw02 instructions encourage the use of DT::datatable, while the tidy submission guidelines instruct us to use a format viewable on github such as github_document and pdf_document. As far as I can tell, DT::datatable only works with html_document format as DT is [producing HTML widgets](https://rstudio.github.io/DT/). 

If I try to knit to either format, I get errors. 

>Error: Functions that produce HTML output found in document targeting gfm-ascii_identifiers output.
Please change the output type of this document to HTML. Alternatively, you can allow
HTML output in non-HTML formats by adding this option to the YAML front-matter of
your rmarkdown file:
  always_allow_html: yes

[link to reprex](https://github.com/trevor-baker/STAT545-participation/tree/master/Assignments/Assignment_02/reprex%20issue)

I've tried 'always_allow_html' in my YAML header but that just lets my Rmd knit without errors but the datatable functions don't work when viewing the file that gets knit. Is there something else to try?

Thanks!

**Comment by wvictor14** [comment]
Yes you are right that `DT::datatable` will only work for html documents. If you choose to knit html, feel free to use it. Otherwise, if you are knitting to markdown or pdf, use another method like `kable`. You will not lose marks for using the appropriate functions for a given filetype.

**Comment by trevor-baker** [comment]
Thanks, Victor!
