### ISSUE TITLE
Requesting office hour this afternoon

### ISSUE THREAD

**Issue by skcan57** [STAT545-UBC-hw-2019-20/Announcements#18]
Hi! I was wondering if someone will be on campus and could meet with me around 2:30 this afternoon - I have some debugging problems with codes for assignment 2. I unfortunately won't be able to come to today's office hour from 11-12pm due to conflicting schedule.

Thank you very much in advance for your accommodation!

Sam

**Comment by vincenzocoia** [comment]
Sure! Just drop by my office, ESB 3172.
