### ISSUE TITLE
Assignment 03 is released

### ISSUE THREAD

**Issue by vincenzocoia** [STAT545-UBC-hw-2019-20/Announcements#21]
Hi everyone! Assignment 03 is ready, and can be found [here](https://stat545.stat.ubc.ca/evaluation/hw03/hw03/) (also from the Assignments home page).

**Comment by hanrach** [comment]
The link is not working. Also when I navigate to the home page, the clickable link is gone.

**Comment by firasm** [comment]
Hello, can you try again? It seems to be working for me.
