### ISSUE TITLE
Error making Github Pages site

### ISSUE THREAD

**Issue by pennykahn** [STAT545-UBC-hw-2019-20/Announcements#22]
Hi!

I tried to connect my homework repository to a github pages site and got this error:
"Your site is having problems building: The value '"9/20/2019"' was passed to a date-related filter that expects valid dates in /_layouts/default.html or one of its layouts. For more information, see https://help.github.com/en/articles/page-build-failed-date-is-not-a-valid-datetime."

Do you guys know what I can do to remedy this situation? 

Thanks,

Penny

**Comment by armetcal** [comment]
I had this problem too. It seems to happen when you've specified the date in your YAML headers, and the date precedes the current date - AKA if I understand correctly, you'd have to go fix every YAML header in your older assignments. I just made a new repository that I'm dedicating to html assignments, and am going to link to the website output in my hw03 README.md file 👍

**Comment by pennykahn** [comment]
I just removed all the dates in the YAML headers from my homework assignments and it's working now. Thanks!

**Comment by yuliaUU** [comment]
Hey,

yes, if you putt in dates it should be a proper formatted: 
explanations can be found [here](https://help.github.com/en/articles/troubleshooting-jekyll-build-errors-for-github-pages-sites#invalid-post-date)
Invalid post date
This error means that a post on your site contains an invalid date in the filename or YAML front matter.

To troubleshoot, make sure all dates are formatted as YYYY-MM-DD HH:MM:SS for UTC and are actual calendar dates. To specify a time zone with an offset from UTC, use the format YYYY-MM-DD HH:MM:SS +/-TTTT, like 2014-04-18 11:30:00 +0800.

If you specify a date format in your _config.yml file, make sure the format is correct.
