### ISSUE TITLE
Assignment 4 Exercise 3.3 clarification

### ISSUE THREAD

**Issue by t-wang-ecohydro** [STAT545-UBC-hw-2019-20/Announcements#27]
Hello,

Quick question for Exercise 3.3: when it says to make a guestlist that includes everyone we have emails for, does the format of the guestlist stay the same as the `guest` dataset? I.e. the table includes `meal_wedding`, `attendance_brunch`, etc. but not `email`.

**Comment by vincenzocoia** [comment]
Up to you!
