### ISSUE TITLE
Peer Review 02 Submitted Incorrectly

### ISSUE THREAD

**Issue by jimmyliu1326** [STAT545-UBC-hw-2019-20/Announcements#28]
I have accidentally submitted the URLs to my peer reviews for HW02 using the HW03 submission on Canvas. I have now corrected it, but it has resulted in my HW02 peer review submission to be considered late. However, I did complete the peer reviews prior to the deadline last week, which can be validated by checking the dates I have opened the github issues for HW02 peer review. So, I hope this can be overlooked, if possible.

Jimmy Liu

**Comment by yuliaUU** [comment]
@jimmyliu1326 . Can you resubmit it?

**Comment by yuliaUU** [comment]
Hey! I am going to mark all of your assignments today! I know that you have been registered late to canvas and it may caused you some issues when submitting everything at once. I will not deduct points for that
