### ISSUE TITLE
Class Meeting 11

### ISSUE THREAD

**Issue by firasm** [STAT545-UBC-hw-2019-20/Announcements#29]
Good afternoon students! 

Excited to be teaching you tomorrow how to load in external data into R and start doing some data exploration with "real" data !

In preparation for the lecture tomorrow, please bring in a dataset from your PhD/MSc research that you are interested importing into R.

If someone would like me to use their datasets as part of the demo, please post the dataset (make sure you're allowed to post on GitHub.com, it goes through US servers so please do not post any  personably identifiable information). You can also send me an email with the dataset (Firas.moosvi@ubc.ca) but I'd prefer a list on this GitHub issue.

If you need to check with your supervisor before sharing the data, you should do so. Either way, you don't have to share the data here if it is private or sensitive, you can just bring it with you tomorrow to use it.

Look forward to tomorrow!

Cheers,

Firas

P.S. the guidebook is not currently accurate for CM011, I'll be bringing in slides and go through with them. Will post them after class.

**Comment by NarayanGopinathan** [comment]
Hi Firas,
This is an important topic and I am excited to learn about it, but I am not
sure that I have an appropriate dataset to use for this lesson. Are there
criteria that it should meet?

There is a dataset I have on the GHG intensity of oil production in
different oil producing nations. Would it work for this? If not, is there a
sample dataset I can use?

Best,
Narayan

**Comment by firasm** [comment]
I will have sample data sets for you to choose from if you don’t bring your own no worries!

The one you pointed out is probably fine as long as it’s tab separated, comma separated, or a basic spreadsheet.

**Comment by firasm** [comment]
URL for greatest givers: http://gattonweb.uky.edu/sheather/book/docs/datasets/GreatestGivers.xls

**Comment by firasm** [comment]
file to load in for class demo 
[Firas-MRI.xlsx](https://github.com/STAT545-UBC-hw-2019-20/Announcements/files/3703782/Firas-MRI.xlsx)
