### ISSUE TITLE
Question about Participation 

### ISSUE THREAD

**Issue by iamurphy** [STAT545-UBC-hw-2019-20/Announcements#35]
I have a question regarding the participation submissions. On the course web page, it says:

"Note that instructor copy is just for your reference. You cannot just copy-paste the code written by the instructors and submit it as your participation. It is the responsibility of every student to be aware and adhere to the policies on plagiarism: Code Plagiarism."

I thought the entire point of the participation component was to download the cmXXX-exercise.Rmd files and go through them during lecture by replacing the FILL_THIS_IN parts with the stuff that the lecturer is doing? Isn't this the same as copying the instructors' code and hence plagiarizing? Can you please clarify if this is correct or not?

**Comment by mksm1228** [comment]
@firasm I also wanted to add that we did not go through some of the questions in the cm exercises. Are we expected to complete them?

**Comment by yuliaUU** [comment]
So , about the copy -pasting: instructor notes does not have everything. You might need to add comments or some explanations/clarifications (sometimes we add/remove some function or try smth else), so it would be nice if you had a note about that, but again it is not a must do. We just want to see that you actually worked in class and not just copy paste what instructor is doing.
 Of course the code you cant change too much, but you can use different numbers, choose different countries and etc.l where possible

Only things you did in class is required!
