### ISSUE TITLE
Assignment 5 instruction

### ISSUE THREAD

**Issue by hanrach** [STAT545-UBC-hw-2019-20/Announcements#36]
I needed some clarification on this instruction, I don't quite get what it means.

"NEW: Like in Assignment 03 and 04, you are also expected to link to any html files that you produce, as a webpage. But, this time, this is only if you produce an HTML file in your homework."

What does it mean by "only if you produce an HTML file in your homework"? Didn't we always do that?

**Comment by firasm** [comment]
It was also possible to submit PDF documents and md files I believe. This guideline won’t apply to those situations...

Hope that helps!

Firas
