### ISSUE TITLE
Question about the participation submission on Canvas

### ISSUE THREAD

**Issue by SL-Ivy** [STAT545-UBC-hw-2019-20/Announcements#38]
I checked the Canvas assignment page, and I found there are two submission items for participation. I did submit the link at the very beginning of the class under the participation, but here is another one. I am confusing about that. Since the course guide mentions if we submit the link right after we create the repo, it will be used for future grading at the end of the term. I don't know if we need to submit it twice. Could you clarify that? Thank you, the STAT 545 team.
![image](https://user-images.githubusercontent.com/55447368/67331920-3cfcfb80-f4d3-11e9-93de-8d54dac1b8f3.png)

**Comment by dy-lin** [comment]
I believe the one at the beginning of the semester was so the TAs knew where your participation repo was (and your GitHub username). The later submission is supposed to be a link to the tagged release of your participation repo.

**Comment by SL-Ivy** [comment]
But it says like the screenshot below...that's why I don't pay attention to the second one which appeared later there.
![image](https://user-images.githubusercontent.com/55447368/67333758-f5c43a00-f4d5-11e9-81e5-ac6ae6fe58d0.png)
![image](https://user-images.githubusercontent.com/55447368/67333787-02489280-f4d6-11e9-8373-0e0cbe3bd283.png)

**Comment by dy-lin** [comment]
What I mean is, I think it's the same logic as submitting the tagged release of the assignments -- it just makes the TAs lives easier, but isn't really necessary. They'll just look at the last commit before the deadline, or a tagged release if you have one.

**Comment by SL-Ivy** [comment]
Ok ok, I see. Thank you a lot!
