### ISSUE TITLE
Taking the course unofficially

### ISSUE THREAD

**Issue by azmigueldario** [STAT545-UBC-hw-2019-20/Announcements#4]
Good day 

I wanted to take the course but it conflicted with my schedule. 
Now I see that some participants have dropped out. I was thinking of following all exercises by myself, given all available guidance on the course page. 
Would that be okay??

Thanks

**Comment by vincenzocoia** [comment]
Hi @azmigueldario, ESB 2012 (the room STAT 545A is held in) is unfortunately at capacity, so being present during lectures would not be feasible. I do recommend following along with the material, though, found at stat545.stat.ubc.ca!
