### ISSUE TITLE
Assignment 1 released on Canvas and deadline reminder

### ISSUE THREAD

**Issue by firasm** [STAT545-UBC-hw-2019-20/Announcements#5]
Dear students,

Two reminders:

1. Just a quick reminder about the deadline for Assignment 1: **Tuesday September 17th at 11:59PM**. 

    - Though the deadline is at midnight, we recommend that you complete the bulk of the content before Tuesday's class and just leave the finishing touches to the last minute.

1. You are now able to submit a link to your assignment on [Canvas](https://canvas.ubc.ca/courses/43352/assignments/388051). 

    - Take note of the rubric that we will use to grade your submissions!

Best of luck, and see you next week!

**Comment by dy-lin** [comment]
For the presentation slides, is `.html` file (like we did in class) okay, or do we need to `knit` to `.pdf` (i.e. GitHub renderable file) like it says in the rubrics?

**Comment by vincenzocoia** [comment]
> For the presentation slides, is .html file (like we did in class) okay, or do we need to knit to .pdf

Either, but it would make our lives easier if you output to pdf.
